const ProductApiActionTypes = {
  START_TO_GET_PRODUCTS_INFORMATION: "START_TO_GET_PRODUCTS_INFORMATION",
  GET_PROD_INFO_SUCCEED: "GET_PROD_INFO_SUCCEED",
  GET_PROD_INFO_FAILED: "GET_PROD_INFO_FAILED",
}

export default ProductApiActionTypes;
